### ISSUE TITLE
C# best practices

### ISSUE THREAD

**Issue by garie** [imagekit-developer/imagekit-dotnet#12]
There are some things about your library that you could do to make it easier to use for .NET developers.

- Fix the need to remove the `IncludeAssets` property when adding the package to references
    - this may only be needed for .NET Framework, which is not commonly used for new projects; I'm not sure, needs research
- Don't name the namespace to be identical to the class
    - If I want to instantiate a new `Imagekit`, I _must_ use `new Imagekit.Imagekit(...)`
    - I don't think you can fix this without breaking backwards compatibility, but this library doesn't appear to be used by a lot of people (maybe because of the issues like this? tbh I find these usability issues difficult enough that I may just copy out the tedious bits code and change it to be how I want it if some of the issues aren't addressed, not sure of your team's speed of response/willingness to change things)
- Use XML doc comments
    - There are IDE extensions that make this easier like [this one](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment) for VSCode
    - I had to read the code to be able to figure out what some of the parameters should be
- Don't use the parameter name `file` to represent a file name or URL 
    - Example: `Utils.PostUpload(apiEndpoint, data, file, path)`
    - I assumed this should be the file contents which cause an exception for a too long URL, which was very confusing and forced me to read the code
    - This parameter is actually the local path or a URL to the file to upload. This should be named something like `filePathOrURL`
- Allow non-static classes to be added to
    - Specifically I wanted to extend `Imagekit` to add an `Upload` method that worked for client-side (see #9)
    - Don't use `private` modifiers on classes that may be inherited, use `protected` to make them available to child classes
        - I wanted to use `IsLocalFile` but had to duplicate the code in my own class
    - You made the class `partial` which only allows you to extend the class within the same assembly. You can leave this but if the intention was to allow private methods to be accessible, it doesn't work that way
- Collections shouldn't be available to write from outside of the class
    - This is a best practice and is definitely a code analysis rule
    - Not doing this actually let me get further in extending the `Imagekit` so I'm kind of 50/50 on this rule - if you stop doing this, you'll need to include a way to add to the `options` collection in `Imagekit`. That being said, I think the implementation of this `options` collection is funky
- Options should be first-class rather than known strings
    - `Imagekit.options` is a dictionary of strings - you have to know what strings to use 
    - Instead it should be an `ImagekitOptions` class with properties like `bool IsPrivateFile`
    - Probably want a `Dictionary<string, string> AdditionalOptions` inside of `ImageKitOptions` for ones that you didn't make first class
- Improper use of async
- I think you may want to turn on code analysis and fix errors and warnings because it will find a lot of these things.

I may come back and update this list as I encounter things. Let me know if this isn't helpful.

**Comment by cloudmeteor** [comment]
Thanks for the suggestions. This is helpful. I'll try to fix thing which are fixable without breaking backward compatibility. PRs are welcome.

**Comment by garie** [comment]
@cloudmeteor I submitted a PR to address some of the filed issues and some of the suggestions here

**Comment by cloudmeteor** [comment]
Thanks @garie. 
PR merged and package published.

**Comment by cloudmeteor** [comment]
Closing this. Created a [separate issue](#26) to track for 1st point.
