### ISSUE TITLE
Image uploads as all black

### ISSUE THREAD

**Issue by garie** [imagekit-developer/imagekit-dotnet#13]
Environment:
- Mac
- .NET Core 3.1

```
var imagekit = new Imagekit.Imagekit(publicKey, privateKey, urlEndpoint);
imagekit.options.Add("folder", "/test/");
imagekit.options.Add("fileName", "testios");
Uri apiEndpoint = new Uri(Imagekit.Util.Utils.GetUploadApi());
var data = imagekit.getUploadData();
var filePath = "/Users/Christi/Library/Photos/pic1.jpg";
var response = Imagekit.Util.Utils.PostUpload(apiEndpoint, data, filePath, privateKey);
var responseContent = await response.Content.ReadAsStringAsync();
```

The status code of `response` is a 200 but the [uploaded image](https://ik.imagekit.io/soundex/soundex/test/testios_hzNsEi4jD3) is entirely black.

**Comment by cloudmeteor** [comment]
Please share the original image which you are trying to upload. Ping us on support chat at [Imagekit.io](https://imagekit.io) for quick response.

**Comment by garie** [comment]
I'm using `Imagekit.Util.Utils.PostUpload` which uploads [as base64](https://github.com/imagekit-developer/imagekit-dotnet/blob/de1678a16d418d6a6b63ef8ec292fb29a1f8eedc/Imagekit/Util/Utils.cs#L151).

I was uploading one of the default images from the iPhone simulator which is not black, but when I dig down into the temp file location it is saved as all black, so I guess it's an issue somewhere else. Closing this.
