### ISSUE TITLE
URL signing has usability issues

### ISSUE THREAD

**Issue by garie** [imagekit-developer/imagekit-dotnet#19]
This is several problems added together which make this library difficult to use for signing without looking at the source code.

In all of the examples, the `f` variable is a `ListAPIResponse` from the `ListFilesAsync` method.

## Problem 1: Specifying both `.Path` and `.Src` does not result in an exception but is not valid.
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation().Width(400).Height(300))
    .Path(f.Url.Replace(urlEndPoint, "/"))
    .Src(f.Url)
    .Signed();
var url = imagekit.Generate();
```
This should result in an exception - behavior here is undefined as `Path` and `Src` could be pointing at different locations. This results in no exception and ignores the `Src` value since `Path` is checked first in code.

## Problem 2: Specifying both `.Src` and `.Signed` does not result in an exception but is not valid.
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation().Width(400).Height(300))
    .Src(f.Url)
    .Signed();
var url = imagekit.Generate();
```
This does not result in a signed url and does not throw an exception. I think signing should be allowed when `Src` is used, but if there is some reason why this shouldn't be allowed, an exception should be thrown when these options are used together.

## Problem 3: `.Path` cannot be set to relative path as it is for other functions
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation().Width(400).Height(300))
    .Path("/myfolder/image.jpg")
    .Signed();
var url = imagekit.Generate();
```
If the `Path` does not start with a `/`, an exception will be thrown because the `Generate` function treats this as a file path even though it should not. You can see some commented out code where the person who wrote this went back and forth:
```
//parsedURL = new Uri((string)options["urlEndpoint"] + (string)options["path"]);
parsedURL = new Uri((string)options["path"]);
```
`parsedURL` is set to `file:///myfolder/image.jpg` now and with the commented out code would have been `https://ik.imagekit.io/myendpoint//myfolder/image.jpg` (note the two slashes). I think this should do some checking and probably not create a `new Uri` out of the specified `Path` since it is not intended to be a URI.

**Update**: Actually it only works at all on unix-based systems. When running on Windows, `.Path("/myfolder/image.jpg")` creates `UriFormatException`.

Horrible workaround:
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation().Width(400).Height(300))
    .Path("https://localhost/myfolder/image.jpg")
    .Signed();
var url = imagekit.Generate();
```

All of the examples in the README set `Path` as a relative path rather than a full URI.

## Problem 4: The signing function is named `Generate`
You can't change this without breaking backwards compatibility, but it should really be named something like `GeneratedSignedUrl`.

## Problem 5: Transformation is required by SDK but not API
You cannot call `Generate` without having specified a `Transformation`.
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation())
    .Path(f.Url.Replace(urlEndPoint, "/"))
    .Signed();
var url = imagekit.Generate();
```
This code generates a url like this, which results in a 404: `https://ik.imagekit.io/myendpoint/tr:/myfolder/image.jpg?ik-s=mysignature`
This is a valid signed url with no transformation: `https://ik.imagekit.io/myendpoint/myfolder/image.jpg?ik-s=mysignature`

## Problem 6: You can't sign a thumbnail URL
An example thumbnail URL is `https://ik.imagekit.io/myendpoint/tr:n-media_library_thumbnail/myfolder/image.jpg`. Note that it has a transformation of `n-media_library_thumbnail` specified.
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation().Width(100).Height(100))
    .Path(f.Thumbnail.Replace(urlEndPoint, "/"))
    .Signed();
var url = imagekit.Generate();
```
This code generates a url like `https://ik.imagekit.io/myendpoint/tr:h-100,w-100/tr:n-media_library_thumbnail/myfolder/image.png?ik-s=mysignature` which is not valid.
I would expect to be able to do something like `.Url(new Transformation().Thumbnail())`

I did find a workaround for this which took me a couple of hours of debugging through the library source code and reading the API docs:
```
var imagekit = new ServerImagekit(publicKey, privateKey, urlEndPoint)
    .Url(new Transformation().Add("n", "media_library_thumbnail"))
    .Path(f.Url.Replace(urlEndPoint, "/"))
    .Signed();
var url = imagekit.Generate();
```

**Comment by cloudmeteor** [comment]
Fixed in b86e70ec1f44a5996652fed6835240d6f5cd6a6a
