### ISSUE TITLE
Image only uploads from file if path length is not divisible by 4

### ISSUE THREAD

**Issue by garie** [imagekit-developer/imagekit-dotnet#22]
In `Utils.PostUploadAsync`, there's an if statement which only reads the contents of the file into the `HttpContent` if the file path is not divisible by 4, the path has a space in it, or inexplicably if the file path is empty, which would certainly just cause an error.

```cs
if (string.IsNullOrEmpty(filePath) || filePath.Length % 4 != 0
    || filePath.Contains(" ") || filePath.Contains("\t") || filePath.Contains("\r") || filePath.Contains("\n"))
```

I can't think of any reason any of this if statement should be there. I just spent hours trying to figure out why some of my photos were uploading as `non-image` only to discover this line of code.

**Comment by cloudmeteor** [comment]
Fixed in 8be428a229330af9d1c5f857d63cf33b2865c2ba
