### ISSUE TITLE
Upload fails with the latest NuGet package

### ISSUE THREAD

**Issue by mstijak** [imagekit-developer/imagekit-dotnet#25]
Upload of images is failing when using the latest NuGet package. It's very hard to figure out what is the problem. The error is related to deserializing JSON, but it might be something else. 

Using an older version works.

**Comment by cloudmeteor** [comment]
Fixed in new [version 3.1.2](https://www.nuget.org/packages/Imagekit/). Please update and retry.

**Comment by mstijak** [comment]
Upload works, but deletion doesn't work. It throws an exception, even though it seems that the image is deleted on the server.

 Object reference not set to an instance of an object.

**Comment by cloudmeteor** [comment]
Fixed in the new release.
