### ISSUE TITLE
How can I search the file name

### ISSUE THREAD

**Issue by ibrdmz** [imagekit-developer/imagekit-dotnet#29]
Searching by file name works if we start typing from the beginning of the file name.
but an advanced search is needed. For example, if the file name is "abcdef1234.jpg", I should be able to find the file when I type "def12" in search.

**Comment by imagekitio** [comment]
@ibrdmz this depends on the [file list API](https://docs.imagekit.io/api-reference/media-api/list-and-search-files) capabilities and not this particular SDK. So closing this one. 

At the moment list API only supports search by full name or with a prefix, however, I have forwarded your request to the product development team.
