### ISSUE TITLE
X and Y Negative Values

### ISSUE THREAD

**Issue by cw-andrews** [imagekit-developer/imagekit-dotnet#31]
The API supports negative values for X and Y via pre-pending the value with **N**

https://docs.imagekit.io/features/image-transformations/overlay#overlay-x-position-ox

However, imakekit-dotnet fails to handle this situation as all of the methods related to coordinates, such as OverlayX and OverlayY, take ints. 

My suggestion would be to keep the method signatures as they are, but pre-pend the N with the absolute value of the passed int.

Regardless, it is an issue, and I just wanted to let you know (I am researching the platform for my companies needs) and don't have the time to create a pull request, etc, especially considering that I am not super familiar with the code).

Thanks!

**Comment by cloudmeteor** [comment]
Thanks for reporting. I'll check this.

**Comment by cw-andrews** [comment]
@cloudmeteor My company decided to use imagekit for something we are doing and I need this issue fixed. I opened a PR with tests. If it is agreeable I would like to get it merged and an update pushed as soon as possible.

Please let me know if there is anything else I need to do regarding this.

**Comment by cloudmeteor** [comment]
@cw-andrews Thanks for the PR. It is merged and new version released.
