### ISSUE TITLE
How to remove background and make image transperent?

### ISSUE THREAD

**Issue by JigarPrajpati** [imagekit-developer/imagekit-dotnet#36]
I'm using C# library for imagekit.io

I'm not able to find any sollution to remove background by upload timeor get time or update time. i can't able to find any way with chain or lamda or any way.

**Comment by imagekitio** [comment]
You can use [background removal extension](https://docs.imagekit.io/extensions/overview/background-removal#webhooks). Here is the sample code - https://github.com/imagekit-developer/imagekit-dotnet/blob/master/ImageKitSample/Program.cs#L186
