### ISSUE TITLE
Enable Support for applying pre-post transformation while uploading assets using SDK

### ISSUE THREAD

**Issue by ashishleo10** [imagekit-developer/imagekit-dotnet#62]
Enable Support for applying [pre-post transformation](https://docs.imagekit.io/features/pre-post-transformation) while uploading assets to ImageKit's Media Library using SDK.

**Comment by ankur-dwivedi** [comment]
The [pre-post transformation](https://docs.imagekit.io/features/pre-post-transformation) feature is now available. Please use SDK version 5.0.0 to access it.
