### ISSUE TITLE
Nuget package is not working with .Net core 2.2

### ISSUE THREAD

**Issue by yahya99223** [imagekit-developer/imagekit-dotnet#7]
Hi, 
After I install your NuGet package on a .Net core 2.2 project, when I try to add it to usings, I still get "the type or namespace 'ImageKit' couldn't be found"

**Comment by cloudmeteor** [comment]
I think there is a typo in using statement. It is Imagekit with small k. 
try `using Imagekit;`

**Comment by netofontess** [comment]
Hi!


I just added the package with Package Manager:
![image](https://user-images.githubusercontent.com/5302167/83664726-bf3cba80-a5a0-11ea-93bf-a965a20b70f8.png)

When I tried include the library, I get the error:
![image](https://user-images.githubusercontent.com/5302167/83664812-ea270e80-a5a0-11ea-96b7-7e057075fdc1.png)

**Comment by cloudmeteor** [comment]
Did it solve your problem?
If not, please check your packageReference in your csproj file. It should contain the following.
<PackageReference Include="Imagekit" Version="3.0.3"></PackageReference>

**Comment by netofontess** [comment]
No!
But your solution, yes.
Change the:
![image](https://user-images.githubusercontent.com/5302167/83670921-46daf700-a5aa-11ea-8a92-a0f7bf2e3f1d.png)

To:
![image](https://user-images.githubusercontent.com/5302167/83670961-50645f00-a5aa-11ea-81aa-88c95c1adf24.png)
